name: 寧の小棧
author: 且宁
url: https://ning-qie.github.io
domain: https://ning0.top
avatar: https://ning-blog-1304206373.cos.ap-nanjing.myqcloud.com/image/something/Avatar.jpg
favicon: https://ning-blog-1304206373.cos.ap-nanjing.myqcloud.com/image/something/favicon.png
