name: Ning
author: 且宁
url: https://ning-qie.github.io
domain: https://ning0ing.com
avatar: https://ning-blog-1304206373.cos.ap-nanjing.myqcloud.com/image/something/Avatar.jpg
favicon: https://ning-blog-1304206373.cos.ap-nanjing.myqcloud.com/image/something/favicon.png
